/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobd;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projetobd.Model.Aluno_RN;
import projetobd.Model.Aluno_VO;

/**
 *
 * @author JonathanRLima
 */
public class FAluno extends javax.swing.JFrame {

    /**
     * Creates new form FAluno
     */
    Aluno_VO alunoVO;
    Aluno_RN alunoRN;

    public FAluno() {
        initComponents();
    }

    public FAluno(Aluno_VO vo) {
        initComponents();
        try {
            alunoVO = vo;
            alunoRN = new Aluno_RN();

            this.jTXFCPF.setText(alunoVO.getCpf());
            this.jTXFGrr.setText(alunoVO.getPk_grr());
            this.jTXFNome.setText(alunoVO.getNome());
            this.jTXFSexo.setText(alunoVO.getSexo());
            this.jTXFDataNascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(alunoVO.getDatanascimento()));
            this.jTXFNomeSocial.setText(alunoVO.getNomesocial());
            this.jPASSenha.setText(alunoVO.getSenha());
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTXFDataNascimento = new javax.swing.JTextField();
        jTXFNomeSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTXFGrr = new javax.swing.JTextField();
        jTXFNome = new javax.swing.JTextField();
        jTXFCPF = new javax.swing.JTextField();
        jTXFSexo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBTNEditar = new javax.swing.JToggleButton();
        jBTNExcluir = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jPASSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTXFGrrNew = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTXFNomeNew = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTXFNomeSocialNew = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTXFCPFNew = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTXFSexoNew = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTXFDataNascimentoNew = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPASSenhaNew = new javax.swing.JPasswordField();
        jBTNCadastrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aluno");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("CPF:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        jLabel5.setText("Data de Nascimento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, -1));
        jPanel1.add(jTXFDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 321, -1));
        jPanel1.add(jTXFNomeSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 321, -1));

        jLabel6.setText("Nome Social:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        jLabel1.setText("GRR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jTXFGrr.setEditable(false);
        jPanel1.add(jTXFGrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 321, -1));
        jPanel1.add(jTXFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 321, -1));
        jPanel1.add(jTXFCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, 321, -1));
        jPanel1.add(jTXFSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 321, -1));

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));

        jBTNEditar.setText("Alterar Cadastro");
        jBTNEditar.setToolTipText("Alterar Cadastro");
        jBTNEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jBTNEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        jBTNExcluir.setText("Excluir Cadastro");
        jBTNExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBTNExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 335, 114, -1));

        jLabel7.setText("Senha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 277, -1, -1));
        jPanel1.add(jPASSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, 320, -1));

        jTabbedPane1.addTab("Visualizar/Alterar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("GRR:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel2.add(jTXFGrrNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 321, -1));

        jLabel16.setText("Nome:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));
        jPanel2.add(jTXFNomeNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 321, -1));

        jLabel17.setText("Nome Social:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));
        jPanel2.add(jTXFNomeSocialNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 321, -1));

        jLabel18.setText("CPF:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));
        jPanel2.add(jTXFCPFNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, 321, -1));

        jLabel19.setText("Sexo:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));
        jPanel2.add(jTXFSexoNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 321, -1));

        jLabel20.setText("Data de Nascimento:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, -1));
        jPanel2.add(jTXFDataNascimentoNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 321, -1));

        jLabel21.setText("Senha:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 277, -1, -1));
        jPanel2.add(jPASSenhaNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, 320, -1));

        jBTNCadastrar.setText("Cadastrar");
        jBTNCadastrar.setToolTipText("Alterar Cadastro");
        jBTNCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(jBTNCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, 100, -1));

        jTabbedPane1.addTab("Novo Cadastro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Visualizar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTNEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNEditarActionPerformed
        try {
            alunoVO.setCpf(this.jTXFCPF.getText());
            alunoVO.setNome(this.jTXFNome.getText());
            alunoVO.setSexo(this.jTXFSexo.getText());
            String dataString = this.jTXFDataNascimento.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataNascimento = new java.sql.Date(fmt.parse(dataString).getTime());

            alunoVO.setDatanascimento(dataNascimento);
            alunoVO.setNomesocial(this.jTXFNomeSocial.getText());
            alunoVO.setSenha(new String(this.jPASSenha.getPassword()).trim());

            if(alunoRN.editarAluno(alunoVO))
                JOptionPane.showMessageDialog(null,"Aluno Alterado");

        } catch (ParseException ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTNEditarActionPerformed

    private void jBTNCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNCadastrarActionPerformed
        try {
            alunoVO.setPk_grr(this.jTXFGrrNew.getText());
            alunoVO.setCpf(this.jTXFCPFNew.getText());
            alunoVO.setNome(this.jTXFNomeNew.getText());
            alunoVO.setSexo(this.jTXFSexoNew.getText());
            String dataString = this.jTXFDataNascimentoNew.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataNascimento = new java.sql.Date(fmt.parse(dataString).getTime());

            alunoVO.setDatanascimento(dataNascimento);
            alunoVO.setNomesocial(this.jTXFNomeSocialNew.getText());
            alunoVO.setSenha(new String(this.jPASSenhaNew.getPassword()).trim());

            //se sucesso, recarregar aba alterações
            if (alunoRN.inserirAluno(alunoVO)) {
                this.jTXFCPF.setText(alunoVO.getCpf());
                this.jTXFGrr.setText(alunoVO.getPk_grr());
                this.jTXFNome.setText(alunoVO.getNome());
                this.jTXFSexo.setText(alunoVO.getSexo());
                this.jTXFDataNascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(alunoVO.getDatanascimento()));
                this.jTXFNomeSocial.setText(alunoVO.getNomesocial());
                this.jPASSenha.setText(alunoVO.getSenha());
                JOptionPane.showMessageDialog(null,"Aluno Inserido");
            }

        } catch (ParseException ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTNCadastrarActionPerformed

    private void jBTNExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNExcluirActionPerformed
        try {
            //se sucesso, recarregar aba alterações
            if (alunoRN.excluirAluno(alunoVO)) {
                JOptionPane.showMessageDialog(null,"Aluno Excluido");
                this.setVisible(false);
                new FLogin().setVisible(true);
            }

        } catch (ParseException ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBTNExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBTNCadastrar;
    private javax.swing.JToggleButton jBTNEditar;
    private javax.swing.JToggleButton jBTNExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPASSenha;
    private javax.swing.JPasswordField jPASSenhaNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTXFCPF;
    private javax.swing.JTextField jTXFCPFNew;
    private javax.swing.JTextField jTXFDataNascimento;
    private javax.swing.JTextField jTXFDataNascimentoNew;
    private javax.swing.JTextField jTXFGrr;
    private javax.swing.JTextField jTXFGrrNew;
    private javax.swing.JTextField jTXFNome;
    private javax.swing.JTextField jTXFNomeNew;
    private javax.swing.JTextField jTXFNomeSocial;
    private javax.swing.JTextField jTXFNomeSocialNew;
    private javax.swing.JTextField jTXFSexo;
    private javax.swing.JTextField jTXFSexoNew;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
